// === USER DASHBOARD ===
app.get('/app', (req, res) => {
  const html = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0"/>',
    '<title>Dashboard</title>',
    '<style>',
    '* { margin: 0; padding: 0; box-sizing: border-box; }',
    'body {',
    '  font-family: system-ui, -apple-system, BlinkMacSystemFont, \'Segoe UI\', sans-serif;',
    '  background: #0c1a3a;',
    '  color: #1e3a8a;',
    '  line-height: 1.5;',
    '  padding: 0 1rem;',
    '  max-width: 480px;',
    '  margin: 0 auto;',
    '  min-height: 100vh;',
    '  display: flex;',
    '  flex-direction: column;',
    '  justify-content: flex-start;',
    '  padding-top: 2vh;',
    '  padding-bottom: 2vh;',
    '  position: relative;',
    '  overflow-x: hidden;',
    '}',
    'body::before {',
    '  content: "";',
    '  position: absolute;',
    '  top: -50%;',
    '  left: -50%;',
    '  width: 200%;',
    '  height: 200%;',
    '  background: radial-gradient(circle, rgba(212, 175, 55, 0.2) 0%, transparent 70%);',
    '  z-index: -1;',
    '  animation: rotate 25s linear infinite;',
    '}',
    '@keyframes rotate {',
    '  from { transform: rotate(0deg); }',
    '  to { transform: rotate(360deg); }',
    '}',
    '.container {',
    '  background: #fff;',
    '  border-radius: 16px;',
    '  padding: 1.6rem;',
    '  margin-bottom: 1.4rem;',
    '  box-shadow: 0 8px 24px rgba(212, 175, 55, 0.15);',
    '  border: 1px solid #f0f0f0;',
    '  width: 100%;',
    '  position: relative;',
    '  z-index: 2;',
    '}',
    'header {',
    '  text-align: center;',
    '  padding: 0.9rem 0;',
    '  margin-bottom: 1.4rem;',
    '  position: relative;',
    '}',
    'h1 {',
    '  font-size: 2.0rem;',
    '  font-weight: 900;',
    '  color: #1e3a8a;',
    '  letter-spacing: -0.5px;',
    '  text-shadow: 2px 2px 4px rgba(212, 175, 55, 0.2);',
    '  position: relative;',
    '  text-align: center;',
    '}',
    'h1::after {',
    '  content: "";',
    '  position: absolute;',
    '  bottom: -8px;',
    '  left: 50%;',
    '  transform: translateX(-50%);',
    '  width: 50px;',
    '  height: 3px;',
    '  background: linear-gradient(90deg, #D4AF37, #FFD700);',
    '  border-radius: 2px;',
    '}',
    '.subtitle {',
    '  color: #555;',
    '  font-size: 0.95rem;',
    '  font-weight: 600;',
    '  margin-top: 0.5rem;',
    '  text-align: center;',
    '}',
    '.card {',
    '  background: #fafafa;',
    '  border-radius: 14px;',
    '  padding: 1.4rem;',
    '  margin-bottom: 1.4rem;',
    '  box-shadow: 0 4px 12px rgba(0,0,0,0.05);',
    '  border: 1px solid #eee;',
    '}',
    '.card h2 {',
    '  color: #D4AF37;',
    '  font-size: 1.3rem;',
    '  margin-bottom: 1.1rem;',
    '  font-weight: 800;',
    '  position: relative;',
    '}',
    '.card h2::after {',
    '  content: "";',
    '  position: absolute;',
    '  bottom: -6px;',
    '  left: 0;',
    '  width: 40px;',
    '  height: 2px;',
    '  background: linear-gradient(90deg, #D4AF37, #FFD700);',
    '  border-radius: 1px;',
    '}',
    'input, select {',
    '  width: 100%;',
    '  padding: 0.85rem;',
    '  margin: 0.55rem 0;',
    '  border: 1px solid #ddd;',
    '  border-radius: 10px;',
    '  font-size: 0.95rem;',
    '  background: #fff;',
    '  color: #333;',
    '  outline: none;',
    '}',
    'input:focus, select:focus {',
    '  border-color: #D4AF37;',
    '  box-shadow: 0 0 0 3px rgba(212, 175, 55, 0.2);',
    '}',
    '.btn-momo {',
    '  background: linear-gradient(135deg, #D4AF37, #FFD700);',
    '  color: #1e3a8a;',
    '  font-weight: 800;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.6px;',
    '  font-size: 1rem;',
    '  padding: 0.85rem 1rem;',
    '  border: none;',
    '  border-radius: 10px;',
    '  width: 100%;',
    '  cursor: pointer;',
    '  box-shadow: ',
    '    0 4px 0 #B8860B,',
    '    0 6px 12px rgba(212, 175, 55, 0.3);',
    '  transition: all 0.15s ease;',
    '  min-height: 48px;',
    '}',
    '#result {',
    '  margin-top: 1rem;',
    '  padding: 1rem;',
    '  border-radius: 10px;',
    '  display: none;',
    '  background: #f0f9ff;',
    '  border-left: 4px solid #3b82f6;',
    '  color: #1e40af;',
    '  font-weight: 600;',
    '  font-size: 0.92rem;',
    '  line-height: 1.5;',
    '}',
    '.mission-note {',
    '  background: #1e3a8a;',
    '  color: white;',
    '  padding: 12px;',
    '  border-radius: 8px;',
    '  margin: 15px 0;',
    '  font-size: 14px;',
    '  text-align: center;',
    '}',
    '#family-pulse {',
    '  background: rgba(30, 58, 138, 0.08);',
    '  border-left: 3px solid #3b82f6;',
    '  padding: 10px;',
    '  border-radius: 0 8px 8px 0;',
    '  margin: 12px 0;',
    '  font-size: 0.9rem;',
    '  color: #1e40af;',
    '  display: none;',
    '}',
    '.theme-toggle {',
    '  background: linear-gradient(135deg, #D4AF37, #FFD700);',
    '  color: #1e3a8a;',
    '  font-weight: 700;',
    '  border: none;',
    '  border-radius: 20px;',
    '  padding: 6px 12px;',
    '  font-size: 0.85rem;',
    '  cursor: pointer;',
    '  box-shadow: 0 2px 0 #B8860B;',
    '  display: block;',
    '  margin: 15px auto;',
    '  width: auto;',
    '  min-height: 40px;',
    '}',
    '.theme-toggle:hover {',
    '  transform: translateY(-1px);',
    '  box-shadow: 0 3px 0 #B8860B, 0 4px 8px rgba(212, 175, 55, 0.3);',
    '}',
    '.footer {',
    '  text-align: center;',
    '  color: #666;',
    '  font-size: 0.8rem;',
    '  padding-top: 1.4rem;',
    '  margin-top: auto;',
    '  border-top: 1px solid #eee;',
    '}',
    '.trademark {',
    '  color: #555;',
    '  font-size: 0.75rem;',
    '  margin-top: 0.5rem;',
    '  font-style: italic;',
    '}',
    '@media (max-width: 600px) {',
    '  .btn-momo {',
    '    width: 100%;',
    '    margin-bottom: 1rem;',
    '  }',
    '}',
    '</style>',
    '</head>',
    '<body>',
    '  <div class="container">',
    '    <header>',
    '      <h1>Dashboard</h1>',
    '      <p class="subtitle">Non-custodial • Alkebulan (AFRICA)-first • Nonprofit-powered</p>',
    '    </header>',
    '',
    '    <div class="mission-note">',
    '      💡 1% solidarity contribution supports our mission.<br/>',
    '      Please remind customers to include Mobile Money network charges when sending funds.',
    '    </div>',
    '',
    '    <div id="family-pulse"></div>',
    '',
    '    <div class="card">',
    '      <h2>Create Mobile Money Payment</h2>',
    '      <input type="text" id="cname" placeholder="Customer Name (e.g. Ama Serwaa)" />',
    '      <input type="text" id="cnum" placeholder="Customer Number (e.g. +233240000000)" />',
    '      <input type="number" id="amt" placeholder="Amount in GHS" min="1" value="100"/>',
    '      <input type="text" id="cphone" placeholder="Customer MoMo number (e.g. +233...)" value="+233240000000"/>',
    '      <button class="btn-momo" onclick="pay()">',
    '        Pay & Empower Alkebulan (AFRICA)',
    '      </button>',
    '      <div id="result"></div>',
    '    </div>',
    '',
    '    <!-- ✅ MY TRANSACTION LEDGER BUTTON — YELLOW GOLD, 3D -->',
    '    <button class="btn-momo" onclick="viewLedger()" style="',
    '      margin-top: 1.2rem;',
    '      background: linear-gradient(135deg, #D4AF37, #FFD700);',
    '      color: #0c1a3a;',
    '      font-weight: 800;',
    '      box-shadow: 0 4px 0 #B8860B, 0 6px 12px rgba(212, 175, 55, 0.4);',
    '    ">',
    '      📖 My Transaction Ledger',
    '    </button>',
    '',
    '    <button class="theme-toggle" onclick="toggleTheme()">🌓 Light/Dark</button>',
    '  </div>',
    '',
    '  <!-- ✅ LEDGER MODAL — BLUE TEXT -->',
    '  <div id="ledgerModal" style="display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.88);z-index:1000;">',
    '    <div style="',
    '      background: rgba(12, 26, 58, 0.96);',
    '      margin: 1.5rem auto;',
    '      padding: 2rem;',
    '      border-radius: 16px;',
    '      width: 92%;',
    '      max-width: 850px;',
    '      max-height: 85vh;',
    '      overflow-y: auto;',
    '      border: 1px solid rgba(255, 215, 0, 0.2);',
    '      box-shadow: 0 12px 40px rgba(255, 215, 0, 0.15);',
    '    ">',
    '      <!-- ✅ BOLD + 3D TITLE -->',
    '      <h2 style="',
    '        color: #FFD700;',
    '        text-align: center;',
    '        margin-bottom: 1.8rem;',
    '        font-size: 1.8rem;',
    '        font-weight: 900;',
    '        text-shadow: 0 2px 0 #B8860B, 0 4px 8px rgba(212, 175, 55, 0.5);',
    '        letter-spacing: -0.5px;',
    '      ">My Transaction Ledger</h2>',
    '',
    '      <table style="width:100%;border-collapse:collapse;margin-top:0.8rem;background:rgba(0,0,0,0.2);border-radius:10px;overflow:hidden;">',
    '        <thead>',
    '          <tr>',
    '            <th style="color:#1e3a8a;font-weight:800;font-size:0.92rem;background:rgba(212,175,55,0.1);padding:0.85rem 0.6rem;text-align:left;">ID</th>',
    '            <th style="color:#1e3a8a;font-weight:800;font-size:0.92rem;background:rgba(212,175,55,0.1);padding:0.85rem 0.6rem;text-align:left;">Date</th>',
    '            <th style="color:#1e3a8a;font-weight:800;font-size:0.92rem;background:rgba(212,175,55,0.1);padding:0.85rem 0.6rem;text-align:left;">Customer</th>',
    '            <th style="color:#1e3a8a;font-weight:800;font-size:0.92rem;background:rgba(212,175,55,0.1);padding:0.85rem 0.6rem;text-align:left;">Amount (GHS)</th>',
    '            <th style="color:#1e3a8a;font-weight:800;font-size:0.92rem;background:rgba(212,175,55,0.1);padding:0.85rem 0.6rem;text-align:left;">Commission (GHS)</th>',
    '            <th style="color:#1e3a8a;font-weight:800;font-size:0.92rem;background:rgba(212,175,55,0.1);padding:0.85rem 0.6rem;text-align:left;">Status</th>',
    '          </tr>',
    '        </thead>',
    '        <tbody id="ledgerBody" style="color:#fff;"></tbody>',
    '      </table>',
    '',
    '      <!-- ✅ EXPORT BUTTON -->',
    '      <button onclick="exportLedger()" style="',
    '        margin-top: 1.2rem;',
    '        background: linear-gradient(135deg, #4ade80, #22c55e);',
    '        color: #0c1a3a;',
    '        font-weight: 700;',
    '        border: none;',
    '        border-radius: 8px;',
    '        padding: 0.7rem 1.2rem;',
    '        cursor: pointer;',
    '        box-shadow: 0 4px 0 #16a34a;',
    '        text-transform: uppercase;',
    '        letter-spacing: 0.5px;',
    '        min-height: 44px;',
    '      ">',
    '        📥 Export Ledger (CSV)',
    '      </button>',
    '',
    '      <button onclick="closeLedger()" style="',
    '        margin-top: 1.5rem;',
    '        background: linear-gradient(135deg, #D4AF37, #FFD700);',
    '        color: #0c1a3a;',
    '        font-weight: 700;',
    '        border: none;',
    '        border-radius: 8px;',
    '        padding: 0.7rem 1.2rem;',
    '        cursor: pointer;',
    '        box-shadow: 0 4px 0 #B8860B;',
    '        text-transform: uppercase;',
    '        letter-spacing: 0.5px;',
    '        transition: all 0.2s ease;',
    '        min-height: 44px;',
    '      ">CloseOperation</button>',
    '    </div>',
    '  </div>',
    '',
    '  <div class="footer">',
    '    © 2026 KS1 Empower Pay – A nonprofit project by KS1 Empire Group & Foundation (KS1EGF)<br/>',
    '    <span class="trademark">Built for Alkebulan (Africa) SMEs, Businesses And Entrepreneurs — united in digital sovereignty and shared prosperity.</span>',
    '  </div>',
    '',
    '  <script>',
    '    let businessPhone = localStorage.getItem(\'businessPhone\');',
    '    if (!businessPhone) {',
    '      alert(\'Please log in first\');',
    '      window.location.href = \'/\';',
    '    }',
    '',
    '    // Auto-logout after 45s',
    '    let inactivityTimer;',
    '    function resetTimer() {',
    '      clearTimeout(inactivityTimer);',
    '      inactivityTimer = setTimeout(() => {',
    '        localStorage.removeItem(\'businessPhone\');',
    '        alert(\'Session expired for security.\');',
    '        window.location.href = \'/\';',
    '      }, 45000);',
    '    }',
    '    [\'click\',\'touchstart\',\'keypress\',\'scroll\'].forEach(e => {',
    '      document.addEventListener(e, resetTimer, true);',
    '    });',
    '    resetTimer();',
    '',
    '    function toggleTheme() {',
    '      const isDark = document.body.classList.contains(\'dark-mode\');',
    '      if (isDark) {',
    '        document.body.classList.remove(\'dark-mode\');',
    '        document.querySelector(\'.container\').style.background = \'#fff\';',
    '        document.querySelector(\'.card\').style.background = \'#fafafa\';',
    '      } else {',
    '        document.body.classList.add(\'dark-mode\');',
    '        document.querySelector(\'.container\').style.background = \'#1e293b\';',
    '        document.querySelector(\'.card\').style.background = \'#334155\';',
    '        document.body.style.color = \'#e2e8f0\';',
    '      }',
    '    }',
    '',
    '    async function pay() {',
    '      const data = {',
    '        businessPhone,',
    '        customerName: document.getElementById(\'cname\').value,',
    '        customerNumber: document.getElementById(\'cnum\').value,',
    '        amount: parseFloat(document.getElementById(\'amt\').value),',
    '        customerPhone: document.getElementById(\'cphone\').value',
    '      };',
    '      const r = document.getElementById(\'result\');',
    '      ',
    '      if (!data.amount || data.amount <= 0 || !data.customerPhone.startsWith(\'+233\')) {',
    '        r.innerHTML = \'Enter valid GHS amount and +233 customer number\';',
    '        r.style.display = \'block\';',
    '        return;',
    '      }',
    '',
    '      r.innerHTML = \'Processing...\';',
    '      r.style.display = \'block\';',
    '',
    '      try {',
    '        const res = await fetch(\'/api/momo/request\', {',
    '          method: \'POST\',',
    '          headers: { \'Content-Type\': \'application/json\' },',
    '          body: JSON.stringify(data)',
    '        });',
    '        const d = await res.json();',
    '        if (d.success) {',
    '          // ✅ NO WHATSAPP RECEIPT — CLEAN CONFIRMATION ONLY',
    '          r.innerHTML = \'<strong>✅ Payment Completed!</strong><br/>Transaction ID: <b>\' + d.transactionId + \'</b><br/>The customer will receive their receipt via WhatsApp.\';',
    '        } else {',
    '          r.innerHTML = \'❌ Failed: \' + (d.error || \'Unknown\');',
    '        }',
    '      } catch (e) {',
    '        r.innerHTML = \'❌ Network error\';',
    '      }',
    '    }',
    '',
    '    // === VIEW TRANSACTION LEDGER ===',
    '    async function viewLedger() {',
    '      try {',
    '        const res = await fetch(\'/api/my-transactions\', {',
    '          method: \'POST\',',
    '          headers: { \'Content-Type\': \'application/json\' },',
    '          body: JSON.stringify({ businessPhone: businessPhone })',
    '        });',
    '        const transactions = await res.json();',
    '        ',
    '        // ✅ Store for export',
    '        localStorage.setItem(\'ledgerData\', JSON.stringify(transactions));',
    '        ',
    '        // ✅ Blue headers, white data, gold ID',
    '        document.getElementById(\'ledgerBody\').innerHTML = transactions.map(tx => ',
    '          `<tr style="border-bottom:1px solid rgba(255,255,255,0.08);">',
    '            <td style="padding:0.85rem 0.6rem;"><code style="font-family:monospace;color:#FFD700;">${tx.transactionId}</code></td>',
    '            <td style="padding:0.85rem 0.6rem;">${new Date(tx.timestamp).toLocaleString()}</td>',
    '            <td style="padding:0.85rem 0.6rem;">${tx.customerName}<br/><small style="color:#94a3b8;">${tx.customerNumber}</small></td>',
    '            <td style="padding:0.85rem 0.6rem;">₵${tx.amount.toFixed(2)}</td>',
    '            <td style="padding:0.85rem 0.6rem;">₵${tx.commission.toFixed(2)}</td>',
    '            <td style="padding:0.85rem 0.6rem;">',
    '              <span style="background:#10b981;color:white;padding:4px 8px;border-radius:6px;font-size:0.85em;font-weight:600;">${tx.status}</span>',
    '            </td>',
    '          </tr>`',
    '        ).join(\'\');',
    '        ',
    '        document.getElementById(\'ledgerModal\').style.display = \'block\';',
    '      } catch (e) {',
    '        alert(\'Failed to load ledger\');',
    '      }',
    '    }',
    '',
    '    function closeLedger() {',
    '      document.getElementById(\'ledgerModal\').style.display = \'none\';',
    '    }',
    '',
    '    // === EXPORT TRANSACTION LEDGER TO CSV ===',
    '    function exportLedger() {',
    '      const transactions = JSON.parse(localStorage.getItem(\'ledgerData\') || \'[]\');',
    '      if (transactions.length === 0) {',
    '        alert(\'No transactions to export.\');',
    '        return;',
    '      }',
    '',
    '      // CSV headers',
    '      const headers = [\'ID\', \'Date\', \'Customer\', \'Customer Number\', \'Amount (GHS)\', \'Commission (GHS)\', \'Status\'];',
    '      let csv = headers.join(\',\') + \'\\n\';',
    '',
    '      // Add rows',
    '      transactions.forEach(tx => {',
    '        const row = [',
    '          `"${tx.transactionId}"`,',
    '          `"${new Date(tx.timestamp).toLocaleString()}"`,',
    '          `"${tx.customerName}"`,',
    '          `"${tx.customerNumber}"`,',
    '          tx.amount.toFixed(2),',
    '          tx.commission.toFixed(2),',
    '          `"${tx.status}"`',
    '        ].join(\',\');',
    '        csv += row + \'\\n\';',
    '      });',
    '',
    '      // Create download',
    '      const blob = new Blob([csv], { type: \'text/csv;charset=utf-8;\' });',
    '      const url = URL.createObjectURL(blob);',
    '      const businessName = localStorage.getItem(\'businessName\') || \'Business\';',
    '      const filename = `KS1_Ledger_${businessName.replace(/\\s+/g, \'_\')}_${new Date().toISOString().slice(0,10)}.csv`;',
    '      ',
    '      const a = document.createElement(\'a\');',
    '      a.href = url;',
    '      a.download = filename;',
    '      document.body.appendChild(a);',
    '      a.click();',
    '      document.body.removeChild(a);',
    '      URL.revokeObjectURL(url);',
    '    }',
    '',
    '    // === FAMILY PULSE ===',
    '    async function loadPulse() {',
    '      try {',
    '        const res = await fetch(\'/api/pulse\');',
    '        const pulses = await res.json();',
    '        if (pulses.length > 0) {',
    '          const latest = pulses[0];',
    '          const pulseEl = document.getElementById(\'family-pulse\');',
    '          pulseEl.textContent = latest.message;',
    '          pulseEl.style.display = \'block\';',
    '          ',
    '          // Glow for new items (< 10 sec old)',
    '          if (Date.now() - new Date(latest.timestamp).getTime() < 10000) {',
    '            pulseEl.style.animation = \'pulseGlow 3s ease-in-out\';',
    '          }',
    '        }',
    '      } catch (e) {',
    '        // Silent fail — pulse is optional',
    '      }',
    '    }',
    '',
    '    // Add CSS animation for glow',
    '    const style = document.createElement(\'style\');',
    '    style.innerHTML = `',
    '      @keyframes pulseGlow {',
    '        0% { background-color: rgba(59, 130, 246, 0.15); }',
    '        50% { background-color: rgba(59, 130, 246, 0.3); }',
    '        100% { background-color: rgba(59, 130, 246, 0.15); }',
    '      }',
    '    `;',
    '    document.head.appendChild(style);',
    '',
    '    // Load on startup + every 30s',
    '    loadPulse();',
    '    setInterval(loadPulse, 30000);',
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');
  res.send(html);
});
